name: Alex McKay
favicon: null
layout_spectrum: 0.97569
typography_spectrum: 0.25517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0077c0'
    - '#64abd7'
    - '#000000'
    - '#d04273'
  brandStrength: 0.75
  lightness: 0.660317124100402
  saturation: 0.5
  rhythmicContrast: 0.22121160966344178
purpose: []
